# -*- coding: utf-8 -*-
"""Image_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgIv7H0SIirvpNRxNKwg65y4t2xlHad2

Install Libraries
"""

!pip install diffusers[torch] transformers accelerate
!pip install matplotlib
!pip install --upgrade torch torchvision

"""Download and Extract Model
Load Pipeline from model directory
"""

from diffusers import StableDiffusionPipeline
import torch

# Automatically download the model from Hugging Face (public repository)
model_name = "CompVis/stable-diffusion-v1-4"

# Load the pipeline directly from the public repository
pipe = StableDiffusionPipeline.from_pretrained(model_name, torch_dtype=torch.float16)
pipe = pipe.to("cuda")  # Use GPU for better performance

"""Generate Image"""

# Take user input for the prompt
prompt = input("Enter your image description prompt: ")

# Generate the image
print("Generating the image, please wait...")
image = pipe(prompt).images[0]

# Display the image inline in Colab
display(image)

# Save the image locally
output_path = "generated_image.png"
image.save(output_path)
print(f"Image saved as {output_path}")